### ISSUE TITLE
Tag stable releases

### ISSUE THREAD

**Issue by akien-mga** [DusteDdk/Wizznic#13]
It would be nice if you could tag past (and future, when they're released ;)) stable releases in this git repo, especially the ones from SourceForge: https://sourceforge.net/projects/wizznic/files/Source%20Releases/

It would in particular make it clearer what new commits have been pushed since 0.9.9 (and if it could be an incentive to finally release 1.0.0, that shouldn't hurt ;)).

**Comment by DusteDdk** [comment]
Agreed, I should really do that :)

**Comment by bentley** [comment]
Yep, this would definitely be helpful for packagers. ☺
