### ISSUE TITLE
Segmentation fault at brick move

### ISSUE THREAD

**Issue by szymor** [DusteDdk/Wizznic#17]
When I try to move a brick, I get Segmentation fault error - dereference of b in board.c at line 485 cannot be done properly:
`
    int deltaX= (b->dx*brickSize+boardOffsetX) - b->pxx ;
`
It seems that the sufficient workaround is to reset a list iterator after each list element removal, like this:
`
      listRemoveItem( pf->movingList, li, LIST_NEXT );
	  li=&pf->movingList->begin;
`
but it needs to be further investigated.

**Comment by DusteDdk** [comment]
Thank you for the report!

It looks like the list does not handle it currectly when removing some element during iteration, probably the very first or very last item.
There are tests in place but I assume they're not correct. I don't think resetting the itereator is correct, I've not dug deep into it but I fear it could make something move an extra time.  I need to dig into the list and get it tested out.
It's amazing though that this has worked fine(tm) so far.

Can you tell me a bit more about this crash? Any particular way to reproduce?
What architecture ?

**Comment by szymor** [comment]
No particular way to reproduce - I just launched the game and I could not
even finish the tutorial because of it. It occurs when I try to move a
brick. The crash does not occur every time but it is much more common than
crashless proper brick movement.

I did not analyse the code thoroughly, I just applied a quick fix that
might have worked (and it works for now). I needed that because I am
porting the game to Bittboy. From my understanding it would increase
complexity of list traversal from O(n) to O(n^2), I am not aware of other
side effects for now. Of course it would be better to fix the list
implementation, but I am not keen to do that by myself :)

The platform I use for development is Arch Linux x64, i3 processor, 4 GB
RAM, nothing fancy.

**Comment by DusteDdk** [comment]
Sorry for the looong response time :) I identified the list related issue and believe I've fixed it, along with a few other minor memory issues.
I see there are still some issues in valgrind, and I will look into those at a later time.
For now, I'd be very happy if you could try and pull the latest code and tell me if the fix works ? :)

**Comment by szymor** [comment]
Sure, I will do it in a couple of days.

**Comment by szymor** [comment]
It seems your patch fixes the issue. I played several levels and could not get any segfault. If I happen to get any memory-related issue, I will create a new ticket for that. Thanks for cooperation :)

**Comment by DusteDdk** [comment]
Excellent, I've also fixed the other errors Valgrind spew at me, I'll do a release soon. Again, thanks for reporting this in! It's really the only way for a small project like this to improve :)
