### ISSUE TITLE
Add an high-res (scalable?) icon for downstream Linux packaging

### ISSUE THREAD

**Issue by akien-mga** [DusteDdk/Wizznic#9]
Hi there,

Linux packagers can currently use data/wmicon.png as an icon when providing a desktop file for integration of Wizznic in the desktop's menu. The file is however only 32x32, so it will look fine in some desktops (e.g. KDE with classical menu), but won't look good in others that show higher res icons (Gnome Shell uses 128x128 or 256x256 IINM).

**Comment by DusteDdk** [comment]
Hi, I'd not mind having a scalable icon, but I've not had the chance to make it.
If you know how to do that in a nice way, I'd be glad to include it along with what you suggest in #10 :)
